id: IF856A144
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T18:56:14+00:00'
last_modified: '2022-06-08T07:53:48.533182+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20239
  title: བོད་ཡིག་ཚེག་སྡེབ་བསླབ་པའི་ཐབས་མཆོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1431':
      image_group_id: I8LS20241
      title: ''
      total_pages: 93
      order: 1
      base_file: 1431.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
